### ISSUE TITLE
compartment names

### ISSUE THREAD

**Issue by SCarter79** [UUPharmacometrics/assemblerr#1]
Using updated assemblerr downloaded on 15-01-2021 at 14.00. When a two compartment IV model is written with V1 and V2, the code does not expand it accordingly in the rendered code:

```
model3 <- pk_model() +
  pk_elimination_linear() +
  pk_distribution_2cmp() +
  compartment('central', volume = ~ V1) +
  compartment('peripheral', volume = ~ V2) +
  obs_additive(conc ~ C['central']) +
  dataset('Genta2.csv') 
```

gives the output where V1=V1 and V2=V2, but the THETAs are written as VC and VP

```
$PROBLEM
$INPUT X ID NEWID OCC TIME AMT RATE DUR DV MDV EVID AGE SEX WT HT IBW CR ACR CLC ACLC ALB WCC BSA
$DATA Genta2.csv IGNORE=@
$SUBROUTINES ADVAN3  TRANS4 
$MODEL COMP=(CENTRAL) COMP=(PERIPHERAL)
$PK
CL = THETA(1) * EXP(ETA(1))
VC = THETA(2) * EXP(ETA(2))
VP = THETA(3) * EXP(ETA(3))
Q = THETA(4) * EXP(ETA(4))
V1 = V1
V2 = V2
$ERROR
CONC = A(1)/V1
Y = CONC + EPS(1)
$ESTIMATION METHOD=COND INTERACTION
$THETA (0, 1, Inf) ; POP_CL
$THETA (0, 1, Inf) ; POP_VC
$THETA (0, 1, Inf) ; POP_VP
$THETA (0, 1, Inf) ; POP_Q
$OMEGA 0.1; IIV_CL
$OMEGA 0.1; IIV_VC
$OMEGA 0.1; IIV_VP
$OMEGA 0.1; IIV_Q
$SIGMA 0.1; RUV_ADD
```

Also is it possible to have the $ESTIMATION at the end of the file as is normally the case?

**Comment by sebastianueckert** [comment]
it should not be necessary to use `compartment()` in connection with a `pk_model` (I should add a warning for that) but maybe the problem was related to issues #3?

**Comment by sebastianueckert** [comment]
I made some changes. Now when you run

``` r
m <- pk_model() + 
  compartment("test")
```

You will get a warning

```
Warning message:
Ignoring 'compartment' building block
x The model does not have a facet 'compartments'
ℹ Not all building blocks can be added to a specific model type 
```
 and the compartment will not be added to the pk_model.

I hope this makes things more clear.

**Comment by SCarter79** [comment]
Thanks for the update. I think I included the compartment originally to define the ‘central’ compartment as it was required in a one compartment model:

```
model1 <- pk_model() +
  pk_elimination_linear() +
  prm_log_normal('V') +
  compartment('central', volume = ~ V) +
  obs_additive(conc ~ C['central']) +
  dataset('Genta2.csv')

## Render model
render(model1)

```

Without the inclusion of ‘compartment('central', volume = ~ V) +’  I get an error:

```
Error in vctrs::field(dcl, "definition") :
  trying to get slot "volume" from an object of a basic class ("NULL") with no slots
```
