### ISSUE TITLE
Incorrect Mu referencing

### ISSUE THREAD

**Issue by SimonBuatois** [UUPharmacometrics/assemblerr#11]
Hi Sebastian,

I just tested the Mu_referencing option in assembler and I don't think that the current implementation can be considered as Mu_referencing.

In fact:

_pkm <- pk_model() +
  pk_absorption_fo() +
  algebraic(S2~1/1000) +
  pk_absorption_fo_lag() +
  pk_distribution_2cmp() +
  pk_elimination_linear() +
  obs_combined(conc~C["central"]*S2)

render(pkm, 
       options = assemblerr_options(prm.use_mu_referencing = TRUE))_

Gives the following output: 
MU_1 = LOG(THETA(1))
MAT = THETA(1) * EXP(ETA(1))
MU_2 = LOG(THETA(2))
MDT = THETA(2) * EXP(ETA(2))
MU_3 = LOG(THETA(3))
VC = THETA(3) * EXP(ETA(3))
MU_4 = LOG(THETA(4))
VP = THETA(4) * EXP(ETA(4))
MU_5 = LOG(THETA(5))
Q = THETA(5) * EXP(ETA(5))
MU_6 = LOG(THETA(6))
CL = THETA(6) * EXP(ETA(6))

However, according to (1) Mu referenced parameters must be defined as follow: 

The user supplies information on how THETA parameters are associated arithmetically with the ETAs and individual parameters:
Phi_j = mu_j(theta) + eta(j)

The association of one or more THETAs with ETA(1) must be identified by a variable called MU_1.

For ETA(2), the variable is MU_2, etc.

For example, suppose the original code is

TVCL=(THETA(1)*(AGE/50)**THETA(2))
CL=TVCL*EXP(ETA(5))
TVV=THETA(3)
V=TVV*EXP(ETA(3))

This code can be modified to include intermediate variables MU_x, which inform NONMEM of the relationship of certain THETAs with certain ETAs:

LTVCL= LOG(THETA(1))+THETA(2)*LOG(AGE/50)
MU_5= LTVCL
LTVV=LOG(THETA(3))
MU_3=LTVV
CL=EXP(MU_5+ETA(5))
V=EXP(MU_3+ETA(3))

(1) NONMEM Tutorial Part II: Estimation Methods and Advanced Examples, Robert J. Bauer

**Comment by SimonBuatois** [comment]
Using the following commande lines I still have the same display.

```
m <- model() +
  prm_log_normal("KA") +
  prm_log_normal("CL") +
  prm_log_normal("V2") +
  prm_log_normal("Q") +
  prm_log_normal("V3") +
  compartment("dose") +
  compartment("central", volume = ~V2) +
  compartment("peripheral", volume = ~V3) +
  flow(from = "dose", to = "central", definition = ~KA*A )+
  flow(from = "central", definition = ~CL/V2*A) +
  flow(from = "central", to = "peripheral", definition = ~Q/V2*A) +
  flow(from = "peripheral", to = "central", definition = ~Q/V3*A) +
  obs_additive(conc~C["central"]) 

render(m,options = assemblerr_options(prm.use_mu_referencing = TRUE))
```
Output:
$PROBLEM
$INPUT ID TIME DV AMT
$DATA data.csv IGNORE=@
$SUBROUTINES ADVAN4  TRANS4 
$PK
**MU_1 = LOG(THETA(1))
KA = THETA(1) * EXP(ETA(1))
MU_2 = LOG(THETA(2))
CL = THETA(2) * EXP(ETA(2))
MU_3 = LOG(THETA(3))
V2 = THETA(3) * EXP(ETA(3))
MU_4 = LOG(THETA(4))
Q = THETA(4) * EXP(ETA(4))
MU_5 = LOG(THETA(5))
V3 = THETA(5) * EXP(ETA(5))**

**Comment by sebastianueckert** [comment]
Should be fixed now
