### ISSUE TITLE
Should a warning be created?

### ISSUE THREAD

**Issue by cossonvalerie** [UUPharmacometrics/assemblerr#14]
Not really an error coding per se by the fact it is mathematically valid, however I wonder if a warning should not be created as it is not usual to have such elimination from the central compartment
m9 <- model() +
  prm_log_normal("vc") +
  prm_log_normal("cl") +
  compartment("central", volume = ~vc) +
  flow(from = "central", definition = ~cl) +
  obs_additive(conc~C["central"])
check(m9)
render(m9)

$PROBLEM
$INPUT ID TIME DV AMT
$DATA data.csv IGNORE=@
$SUBROUTINES ADVAN13 TOL=6
$MODEL COMP=(CENTRAL)
$PK
VC = THETA(1) * EXP(ETA(1))
CL = THETA(2) * EXP(ETA(2))
$DES
DADT("CENTRAL") = -CL
$ERROR
CONC = A(1)/VC
Y = CONC + EPS(1)
$ESTIMATION METHOD=COND INTER
$COVARIANCE PRINT=E
$THETA (0, 1, Inf) ; POP_VC
$THETA (0, 1, Inf) ; POP_CL
$OMEGA 0.1; IIV_VC
$OMEGA 0.1; IIV_CL
$SIGMA 0.1; RUV_ADD

**Comment by sebastianueckert** [comment]
Yes, indeed it is not really an error and I am not sure we should warn here. Unless a zero-order rate constant is indeed almost impossible. 

However, I saw that the compartment names have not been replaced correctly (i.e., it still says `DADT("CENTRAL")`). I will fix that.
