### ISSUE TITLE
Create a model with two $EST (SAEM+IMP)

### ISSUE THREAD

**Issue by SimonBuatois** [UUPharmacometrics/assemblerr#21]
I have an error message when I'm trying to create two $EST:

```
render(pkm,tasks=tsk_estimation(
  algorithm = c("saem", "imp"),
  se = FALSE,
  target_options = list()
))
```

![image](https://user-images.githubusercontent.com/75624013/120182497-c7a8ef00-c20e-11eb-8d51-5f8ae488735e.png)

**Comment by sebastianueckert** [comment]
The documentation of tsk_estimation has been improved and now details how to achieve this.
