### ISSUE TITLE
Questions and suggestions for Assemblerr

### ISSUE THREAD

**Issue by cossonvalerie** [UUPharmacometrics/assemblerr#28]
1) How to include the NOABORT option? 
I have tried the following but it does not work :
render(pkmc5e, tasks=tsk_estimation(algorithm="foce",target_options = list(maxeval = 1000, noabort=TRUE)))
I get $ESTIMATION METHOD=COND INTERACTION MAXEVAL=1000 NOABORT=1
render(pkmc5f, tasks=tsk_estimation(algorithm="foce",target_options = list(maxeval = 1000, "noabort")))
I get an error message: Error: `...` arguments must be either all named, or all unnamed

2) Is this the intended behaviour?
If no tasks are defined in render by default $ESTIMATION is populated with METHOD=COND INTERACTION MAXEVAL=999999. As soon as a task is added to get an output table, the default $ESTIMATION is not populated and will need to be added to the tasks. 

3)  I have noticed that ID is not by default in the output tables. It would be great if by default ID is added. For example with render(pkmd3, tasks=tsk_output_xpose4())
I get
$TABLE DV PRED RES WRES IPREDI IWRESI FILE=sdtab NOAPPEND NOPRINT
$TABLE MAT MDT VC VP Q VMAX KM ETA(1) ETA(2) ETA(3) ETA(4) ETA(5) ETA(6) ETA(7) FILE=patab NOAPPEND NOPRINT

**Comment by sebastianueckert** [comment]
1 and 3 have been fixed. Number 2 is indeed expected behavior as it overwrites the default argument.
