### ISSUE TITLE
Error in coding MM elimination

### ISSUE THREAD

**Issue by cossonvalerie** [UUPharmacometrics/assemblerr#4]
I wanted to create a 1cpt model with FO and MM elimination
pkm2 <- pk_model() +
  pk_absorption_fo_lag() + 
  pk_distribution_2cmp() +
  pk_elimination_mm() +
  obs_combined(conc~C["central"])

render(pkm2)
render(pkm2, filename = "Test2.mod")

There is an error in the $DES coding, it should not be CLMM*KM/(KM+A(2)/VC) but CLMM*(A(2)/VC)/(KM+A(2)/VC) 

$SUBROUTINES ADVAN13 TOL=6
$MODEL COMP=(DEPOT) COMP=(CENTRAL) COMP=(PERIPHERAL)
$PK
...

$DES
DADT(1) = -(KA * A(1))
DADT(2) = KA * A(1) + Q * (A(3)/VP) - (Q * (A(2)/VC) + CLMM * KM/(KM + A(2)/VC))
DADT(3) = Q * (A(2)/VC) - Q * (A(3)/VP)
$ERROR
CONC = A(2)/VC
Y = CONC + EPS(1) + CONC * EPS(2)

**Comment by sebastianueckert** [comment]
This is actually a different parameterization that allows initializing CLMM in an easier manner than Vmax. CLMM is equal to CL when the concentration is much smaller than Km.
We chose this parameterization to make it easier to take the final estimates from a linear elimination model to a Michaelis Menten model (however I wonder now whether it should still be called the Michaelis Menten model).

**Comment by sebastianueckert** [comment]
After some reflection, I have now changed the function from `pk_elimination_mm` to `pk_elimination_nl`. Furthermore, you can now also ask for the more classical parameterization using
``` r
pkm2 <- pk_model() +
  pk_absorption_fo_lag() +
  pk_distribution_2cmp() +
  pk_elimination_nl(prm_vmax = prm_log_normal("vmax"), prm_clmm = NULL) +
  obs_combined(conc~C["central"])
```
