### ISSUE TITLE
Simultaneous Linear and MM elimination

### ISSUE THREAD

**Issue by SimonBuatois** [UUPharmacometrics/assemblerr#5]
Hi Sebastian,

Would it be possible to add the possibility to create a model with both a linear and a non linear elimination ? 
(e.g. k_elimination_linear_mm). This types of models are often used as default in onco.

Kind regards,
Simon

**Comment by sebastianueckert** [comment]
I think that should be quite easy.

**Comment by sebastianueckert** [comment]
This functionality has been added as suggested. 

@SimonBuatois could you please check the implementation?
