### ISSUE TITLE
Auto-check for consistency

### ISSUE THREAD

**Issue by SimonBuatois** [UUPharmacometrics/assemblerr#6]
Possible to auto-check for consistency?
m <- model() +
  prm_log_normal("v1") +
  prm_log_normal("cl") +
  obs_additive(conc~amt/v*exp(-cl/v*time)) 

no error produced

output: 
$PROBLEM
$INPUT ID TIME DV AMT
$DATA data.csv IGNORE=@
$PRED
V1 = THETA(1) * EXP(ETA(1))
CL = THETA(2) * EXP(ETA(2))
CONC = AMT/V * EXP(-CL/V * TIME)
Y = CONC + EPS(1)
$ESTIMATION METHOD=COND INTER
$COVARIANCE PRINT=E
$THETA (0, 1, Inf) ; POP_V1
$THETA (0, 1, Inf) ; POP_CL
$OMEGA 0.1; IIV_V1
$OMEGA 0.1; IIV_CL
$SIGMA 0.1; RUV_ADD

**Comment by sebastianueckert** [comment]
Do you mean checking if all variables have been defined/used? Yes, that should be added.

**Comment by SimonBuatois** [comment]
"Do you mean checking if all variables have been defined/used?"
Yes exactly.

**Comment by sebastianueckert** [comment]
This functionality has been added.
