### ISSUE TITLE
Zero order absorption rate:

### ISSUE THREAD

**Issue by SimonBuatois** [UUPharmacometrics/assemblerr#7]
Hi Sebastian,

This might be a naive question, but in R1 = AMT/MDT/2      ; why/2?

#1-comp open model with lag
pkm <- pk_model() +
  pk_absorption_fo_zo() +
  pk_distribution_1cmp() +
  pk_elimination_linear() +
  obs_additive(conc~C["central"]) 

Output:

$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
KA = 1/MAT
R1 = AMT/MDT/2      ; why/2?
V1 = VC
V2 = VP

**Comment by sebastianueckert** [comment]
I had to ask Rikard too. He said
>It comes from the definition of MAT. MAT is the mean time to absorption (for each mass unit). Then since the ZO-absorption is constant independent of how much has been absorbed the MAT must be when half of the amount has been absorbed
